### ISSUE TITLE
Title Case issue

### ISSUE THREAD

**Issue by Weeesly** [CRModders/cosmic-mod-manager#54]
Using Title Case in Spanish makes the text look odd and inconsistent with grammatical rules. Shouldn't this be handled manually in translations?
![image](https://github.com/user-attachments/assets/7a342140-f4c0-434e-9dec-b980a3d971ab)
![image](https://github.com/user-attachments/assets/644a872b-855c-4608-9995-161d407f2ed1)
![image](https://github.com/user-attachments/assets/aadfbffe-2baa-4dc9-91b0-6a48879cdd31)

**Comment by Abhinav5383** [comment]
Hmm, actually it's a css problem i forgot to remove the `capitalize` from those. Because in english those were one word so it wasn't visible,
will fix it soon

> `text-transform: capitalize` makes the first letter of each word uppercase

**Comment by Abhinav5383** [comment]
Commit [d8dd463](https://github.com/CRModders/cosmic-mod-manager/commit/d8dd463d7799275d6de0be1b2bc449f737e264ce) fixes this issue
